# Generated by Django 5.0.2 on 2024-02-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dopamine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField()),
                ('description', models.CharField(max_length=400)),
                ('motivation', models.CharField(max_length=400)),
            ],
        ),
    ]
