# Generated by Django 5.0.2 on 2024-02-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField()),
                ('description', models.CharField(max_length=400)),
                ('motivation', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Strides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField()),
                ('description', models.CharField(max_length=400)),
                ('motivation', models.CharField(max_length=400)),
                ('steps', models.ManyToManyField(to='steps.steps')),
            ],
        ),
        migrations.AddField(
            model_name='dopamine',
            name='strides',
            field=models.ManyToManyField(to='steps.strides'),
        ),
    ]
