# Generated by Django 5.0.2 on 2024-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_steps_strides_dopamine_strides'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='completed',
            new_name='steps_completed',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='deadline',
            new_name='steps_deadline',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='description',
            new_name='steps_description',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='motivation',
            new_name='steps_motivation',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='title',
            new_name='steps_title',
        ),
        migrations.RenameField(
            model_name='strides',
            old_name='completed',
            new_name='strides_completed',
        ),
        migrations.RenameField(
            model_name='strides',
            old_name='deadline',
            new_name='strides_deadline',
        ),
        migrations.RenameField(
            model_name='strides',
            old_name='description',
            new_name='strides_description',
        ),
        migrations.RenameField(
            model_name='strides',
            old_name='motivation',
            new_name='strides_motivation',
        ),
        migrations.RenameField(
            model_name='strides',
            old_name='title',
            new_name='strides_title',
        ),
        migrations.AlterField(
            model_name='dopamine',
            name='strides',
            field=models.ManyToManyField(blank=True, to='steps.strides'),
        ),
        migrations.AlterField(
            model_name='strides',
            name='steps',
            field=models.ManyToManyField(blank=True, to='steps.steps'),
        ),
    ]
